In [25]:
# convert images to numpy arrays using OpenCV
import cv2
import numpy

In [9]:
# printing image in colors by passing 1 for colors
im_g=cv2.imread("smallgray.png",1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [10]:
# printing image in gray scale passing 0 for back and white
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [11]:
# how to write an image from array
cv2.imwrite("newsmallgray.png",im_g)

True

In [14]:
# indexing,slicing,and iterating numpy arrays
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
im_g.shape

(3, 5)

In [18]:
# or we can print only one value
im_g[2,4]

182

In [19]:
# iterating
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [20]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [22]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [23]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
# stacking and splitting numpy arrays
# stacking horizontally
ims=numpy.hstack((im_g,im_g,im_g))

In [31]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [33]:
# stacking vertically
ims=numpy.vstack((im_g,im_g,im_g))

In [35]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [39]:
# spliting numpy arrays
# spliting horizontally
lst=numpy.hsplit(ims,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [42]:
# spliting vertically
lst=numpy.vsplit(ims,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [44]:
# produces a python list 
type(lst) 

list

In [48]:
# to access first array after spliting in 3 small arrays
#lst[1]
#lst[2]
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)